- src/main/java/org/accounting/system/constraints/ZuluTime.java
- src/main/java/org/accounting/system/dtos/MetricDefinitionDtoRequest.java
- src/main/java/org/accounting/system/dtos/MetricRequestDto.java
- src/main/java/org/accounting/system/dtos/MetricResponseDto.java
- src/main/java/org/accounting/system/endpoints/MetricDefinitionEndpoint.java
- src/main/java/org/accounting/system/endpoints/MetricEndpoint.java
- src/main/java/org/accounting/system/entities/Metric.java
- src/main/java/org/accounting/system/exceptionmappers/BadRequestExceptionMapper.java
- src/main/java/org/accounting/system/exceptionmappers/InvalidFormatExceptionMapper.java
- src/main/java/org/accounting/system/exceptionmappers/MongoWriteExceptionMapper.java
- src/main/java/org/accounting/system/exceptions/ConflictException.java
- src/main/java/org/accounting/system/mappers/MetricDefinitionMapper.java
- src/main/java/org/accounting/system/mappers/MetricMapper.java
- src/main/java/org/accounting/system/repositories/MetricRepository.java
- src/main/java/org/accounting/system/services/MetricDefinitionService.java
- src/main/java/org/accounting/system/services/MetricService.java
- src/main/java/org/accounting/system/validators/ZuluTimeValidator.java
- src/main/resources/db/changeLog.xml
- src/test/java/org/accounting/system/MetricDefinitionEndpointTest.java
- src/test/java/org/accounting/system/MetricEndpointTest.java
Contains the operations which are responsible for creating a new Metric. Also, a query, which generates the Metric collection, has been added to changeLog.xml.
> [ACC-10] Submit a Metric

- src/main/java/org/accounting/system/endpoints/MetricEndpoint.java
- src/main/java/org/accounting/system/repositories/MetricRepository.java
- src/main/java/org/accounting/system/services/MetricDefinitionService.java
- src/main/java/org/accounting/system/services/MetricService.java
- src/test/java/org/accounting/system/MetricEndpointTest.java
GET endpoint has been generated to retrieve an existing Metric.
> [ACC-11] Fetch a Metric

- src/main/java/org/accounting/system/endpoints/MetricEndpoint.java
- src/main/java/org/accounting/system/services/MetricDefinitionService.java
- src/main/java/org/accounting/system/services/MetricService.java
- src/test/java/org/accounting/system/MetricEndpointTest.java
DELETE endpoint has been generated to delete an existing Metric.
> [ACC-12] Delete a Metric

- src/main/java/org/accounting/system/dtos/InformativeResponse.java
- src/main/java/org/accounting/system/dtos/MetricRequestDto.java
- src/main/java/org/accounting/system/dtos/MetricResponseDto.java
- src/main/java/org/accounting/system/dtos/PageLink.java
- src/main/java/org/accounting/system/dtos/PageResource.java
- src/main/java/org/accounting/system/endpoints/MetricDefinitionEndpoint.java
- src/main/java/org/accounting/system/exceptionmappers/UnprocessableExceptionMapper.java
- src/main/java/org/accounting/system/exceptions/UnprocessableException.java
- src/main/java/org/accounting/system/mappers/MetricMapper.java
- src/main/java/org/accounting/system/repositories/MetricRepository.java
- src/main/java/org/accounting/system/services/MetricDefinitionService.java
- src/test/java/org/accounting/system/MetricDefinitionEndpointTest.java
The Metrics of Metric Definition can be paginated.
ACC-21
> [ACC-21] Metric Pagination

- src/main/java/org/accounting/system/constraints/MetricDefinitionNotFound.java
- src/main/java/org/accounting/system/constraints/MetricNotFound.java
- src/main/java/org/accounting/system/constraints/MetricTypeNotFound.java
- src/main/java/org/accounting/system/constraints/UnitTypeNotFound.java
- src/main/java/org/accounting/system/constraints/ValidateStartEndTimestamp.java
- src/main/java/org/accounting/system/dtos/MetricDefinitionRequestDto.java
- src/main/java/org/accounting/system/dtos/MetricDefinitionResponseDto.java
- src/main/java/org/accounting/system/dtos/UpdateMetricDefinitionRequestDto.java
- src/main/java/org/accounting/system/dtos/UpdateMetricRequestDto.java
- src/main/java/org/accounting/system/endpoints/MetricDefinitionEndpoint.java
- src/main/java/org/accounting/system/endpoints/MetricEndpoint.java
- src/main/java/org/accounting/system/exceptionmappers/ValidationExceptionMapper.java
- src/main/java/org/accounting/system/exceptions/CustomValidationException.java
- src/main/java/org/accounting/system/mappers/MetricDefinitionMapper.java
- src/main/java/org/accounting/system/mappers/MetricMapper.java
- src/main/java/org/accounting/system/services/MetricDefinitionService.java
- src/main/java/org/accounting/system/services/MetricService.java
- src/main/java/org/accounting/system/util/Predicates.java
- src/main/java/org/accounting/system/validators/MetricDefinitionNotFoundValidator.java
- src/main/java/org/accounting/system/validators/MetricNotFoundValidator.java
- src/main/java/org/accounting/system/validators/MetricTypeNotFoundValidator.java
- src/main/java/org/accounting/system/validators/UnitTypeNotFoundValidator.java
- src/main/java/org/accounting/system/validators/ValidateStartEndTimestampValidator.java
- src/main/java/org/accounting/system/validators/ZuluTimeValidator.java
- src/test/java/org/accounting/system/MetricDefinitionEndpointTest.java
- src/test/java/org/accounting/system/MetricEndpointTest.java
PATCH endpoint has been generated to update an existing Metric.
ACC-22
> [ACC-22] Update a Metric

- Jenkinsfile
- README.md
A file named Jenkinsfile has been created in the repository root, which contains a pipeline script.
The pipeline script retrieves the relative docker image and runs the unit tests.
ACC-20
> [ACC-20] Generate a Jenkinsfile in the repository root

- files/metric_type.conf
- files/unit_type.conf
- src/main/java/org/accounting/system/entities/MetricDefinition.java
- src/main/java/org/accounting/system/repositories/MetricDefinitionRepository.java
We have added the following types into the unit and metric files:
**_unit_type.conf_**
- Count
- TB
- CPU Time
**_metric_type.conf_**
- count
- averaged
- summarised
> [ACC-29] Introduce new Metric and Unit Types

- README.md
- pom.xml
- src/main/java/org/accounting/system/endpoints/MetricDefinitionEndpoint.java
- src/main/java/org/accounting/system/endpoints/MetricEndpoint.java
- src/main/java/org/accounting/system/templates/KeycloakClientTemplate.java
- src/main/resources/META-INF/resources/index.html
- src/main/resources/application.properties
- src/main/resources/templates/keycloak.html
- src/test/java/org/accounting/system/MetricDefinitionEndpointTest.java
- src/test/java/org/accounting/system/MetricEndpointTest.java
The Accounting System API resources have been protected by an external Keycloak.
What that means practically, is that these resources can only be accessed if a client is sending
a bearer token along with the request, which must be valid and trusted by the Accounting System API.
There also is a UI Page at {accounting_system_host} which is responsible for :
* redirecting a user to Keycloak's login page in order to be authenticated
* displaying the obtained token
> [ACC-24] Authentication Process

- README.md
- src/main/java/org/accounting/system/dtos/RoleResponseDto.java
- src/main/java/org/accounting/system/dtos/authorization/CollectionPermissionDto.java
- src/main/java/org/accounting/system/dtos/authorization/PermissionDto.java
- src/main/java/org/accounting/system/dtos/authorization/RoleRequestDto.java
- src/main/java/org/accounting/system/endpoints/RoleEndpoint.java
- src/main/java/org/accounting/system/repositories/MetricDefinitionRepository.java
- src/main/java/org/accounting/system/repositories/authorization/AccessEntityRepository.java
- src/main/java/org/accounting/system/repositories/authorization/RoleRepository.java
- src/main/java/org/accounting/system/services/MetricDefinitionService.java
- src/main/java/org/accounting/system/services/authorization/RoleService.java
- src/test/java/org/accounting/system/RoleEndpointAuthorizationTest.java
- src/test/java/org/accounting/system/RoleEndpointTest.java
You can retrieve one or all roles.
ACC-44
> [ACC-44] Retrieve Roles

- src/main/resources/db/changeLog.xml
Executed queries in changelog.xml should never be changed.
> Fix changelog.xml 

- Jenkinsfile
- pom.xml
Add jacoco maven plugin to create test coverage reports
> Add jacoco plugin

- src/main/java/org/accounting/system/dtos/metricdefinition/MetricDefinitionResponseDto.java
- src/main/java/org/accounting/system/endpoints/MetricDefinitionEndpoint.java
- src/main/java/org/accounting/system/services/MetricDefinitionService.java
- src/main/java/org/accounting/system/util/QueryParser.java
Metric Definition /search request with role permissions
> ACC-57 Provide and process a search request on a collection to the API with role permissions

- src/main/java/org/accounting/system/endpoints/MetricDefinitionEndpoint.java
- src/main/java/org/accounting/system/endpoints/MetricEndpoint.java
Added example of request body for search request of metric and metric definitions in order to appear to swagger
> add request body example for metric & metric definitions

- src/main/java/org/accounting/system/HierarchicalRelationSerializer.java
- src/main/java/org/accounting/system/dtos/installation/UpdateInstallationRequestDto.java
- src/main/java/org/accounting/system/dtos/project/CorrelateProjectProviderRequestDto.java
- src/main/java/org/accounting/system/endpoints/InstallationEndpoint.java
- src/main/java/org/accounting/system/endpoints/ProjectEndpoint.java
- src/main/java/org/accounting/system/entities/projections/HierarchicalRelationProjection.java
- src/main/java/org/accounting/system/repositories/HierarchicalRelationRepository.java
- src/main/java/org/accounting/system/services/HierarchicalRelationService.java
- src/main/java/org/accounting/system/templates/KeycloakClientTemplate.java
- src/main/java/org/accounting/system/templates/RoleTemplate.java
- src/test/java/org/accounting/system/InstallationAuthorizationTest.java
- src/test/java/org/accounting/system/InstallationEndpointTest.java
- src/test/java/org/accounting/system/ProjectEndpointTest.java
We have exposed a new endpoint that is responsible for correlating many Providers with a Project.
ACC-58
> [ACC-58] Creating the Project-Provider relationship

- src/main/java/org/accounting/system/endpoints/ProjectEndpoint.java
Throw a NotFoundException when there are no any Provider or Installation
correlating with the given Project.
> Hierarchical Structure

- src/main/java/org/accounting/system/dtos/client/ClientResponseDto.java
- src/main/java/org/accounting/system/endpoints/ClientEndpoint.java
- src/main/java/org/accounting/system/endpoints/InstallationEndpoint.java
- src/main/java/org/accounting/system/endpoints/MetricDefinitionEndpoint.java
- src/main/java/org/accounting/system/endpoints/MetricEndpoint.java
- src/main/java/org/accounting/system/endpoints/ProjectEndpoint.java
- src/main/java/org/accounting/system/endpoints/ProviderEndpoint.java
- src/main/java/org/accounting/system/endpoints/RoleEndpoint.java
- src/main/java/org/accounting/system/entities/client/Client.java
- src/main/java/org/accounting/system/enums/AccessType.java
- src/main/java/org/accounting/system/enums/Collection.java
- src/main/java/org/accounting/system/mappers/ClientMapper.java
- src/main/java/org/accounting/system/repositories/client/ClientAccessAlwaysRepository.java
- src/main/java/org/accounting/system/repositories/client/ClientAccessControlRepository.java
- src/main/java/org/accounting/system/repositories/client/ClientAccessEntityRepository.java
- src/main/java/org/accounting/system/repositories/client/ClientModulator.java
- src/main/java/org/accounting/system/repositories/client/ClientRepository.java
- src/main/java/org/accounting/system/services/client/ClientService.java
- src/main/resources/application.properties
- src/main/resources/db/changeLog.xml
- src/test/java/org/accounting/system/ClientEndpointTest.java
- src/test/java/org/accounting/system/MetricEndpointTest.java
- src/test/java/org/accounting/system/ProjectEndpointTest.java
The client can register itself into the Accounting System, passing
the acquired access token to the new endpoint that has been generated.
> [ACC-69] Registration of a client into Accounting System

- src/main/java/org/accounting/system/dtos/project/ProjectResponseDto.java
- src/main/java/org/accounting/system/endpoints/MetricDefinitionEndpoint.java
- src/main/java/org/accounting/system/endpoints/MetricEndpoint.java
- src/main/java/org/accounting/system/endpoints/ProjectEndpoint.java
- src/main/java/org/accounting/system/entities/Project.java
- src/main/java/org/accounting/system/mappers/ProjectMapper.java
- src/main/java/org/accounting/system/repositories/acl/AccessControlRepository.java
- src/main/java/org/accounting/system/repositories/modulators/AccessModulator.java
- src/main/java/org/accounting/system/repositories/project/ProjectRepository.java
- src/main/java/org/accounting/system/services/MetricDefinitionService.java
- src/main/java/org/accounting/system/services/ProjectService.java
- src/main/java/org/accounting/system/util/QueryParser.java
> ACC-60 Apply search feature on Project

- src/main/java/org/accounting/system/dtos/pagination/PageResource.java
- src/main/java/org/accounting/system/endpoints/ProjectEndpoint.java
- src/main/java/org/accounting/system/repositories/modulators/AccessModulator.java
- src/main/java/org/accounting/system/repositories/project/ProjectModulator.java
- src/main/java/org/accounting/system/serializer/PageResourceMixIn.java
- src/main/java/org/accounting/system/services/ProjectService.java
- src/main/resources/application.properties
- src/test/java/org/accounting/system/InstallationAuthorizationTest.java
- src/test/java/org/accounting/system/MetricDefinitionAuthorizationTest.java
- src/test/java/org/accounting/system/MetricDefinitionEndpointTest.java
- src/test/java/org/accounting/system/ProjectAutorizationTest.java
Get all projects permitted for user
> ACC-89 Implement getAll() for Project collection

- src/main/java/org/accounting/system/dtos/pagination/PageResource.java
- src/main/java/org/accounting/system/endpoints/ClientEndpoint.java
- src/main/java/org/accounting/system/endpoints/InstallationEndpoint.java
- src/main/java/org/accounting/system/endpoints/MetricDefinitionEndpoint.java
- src/main/java/org/accounting/system/endpoints/ProjectEndpoint.java
- src/main/java/org/accounting/system/endpoints/ProviderEndpoint.java
- src/main/java/org/accounting/system/endpoints/RoleEndpoint.java
- src/main/java/org/accounting/system/services/MetricDefinitionService.java
- src/main/java/org/accounting/system/services/ProjectService.java
- src/main/java/org/accounting/system/services/ProviderService.java
- src/main/java/org/accounting/system/services/authorization/RoleService.java
- src/main/java/org/accounting/system/services/client/ClientService.java
- src/main/java/org/accounting/system/services/installation/InstallationService.java
The endpoint listing the available Entities has incorrect OpenAPI specifications. It has been defined to return an array of Entities instead of a pageable response.
ACC-91
> [ACC-91] Fix OpenAPI specification

- src/main/java/org/accounting/system/endpoints/MetricDefinitionEndpoint.java
- src/main/java/org/accounting/system/endpoints/ProviderEndpoint.java
- src/main/java/org/accounting/system/repositories/acl/AccessControlRepository.java
- src/main/java/org/accounting/system/services/MetricDefinitionService.java
- src/main/java/org/accounting/system/services/ProviderService.java
> ACC-61 Apply search feature on Provider

- src/main/java/org/accounting/system/endpoints/InstallationEndpoint.java
- src/main/java/org/accounting/system/endpoints/ProjectEndpoint.java
- src/main/java/org/accounting/system/mappers/AccessControlMapper.java
- src/main/java/org/accounting/system/repositories/acl/AccessControlRepository.java
- src/main/java/org/accounting/system/services/acl/AccessControlService.java
We have generated three new endpoints listing the available Access Control Entries for any level of the Project - Provider - Installation relationship.
ACC-92
> [ACC-92] Create new endpoints listing the Access Control Entries

- src/main/java/org/accounting/system/endpoints/ProviderEndpoint.java
- src/main/java/org/accounting/system/repositories/provider/ProviderModulator.java
- src/test/java/org/accounting/system/ProviderEndpointTest.java
You cannot update an existing Provider if it belongs to a Project.
ACC-96
> [ACC-96] Updating an existing Provider is not allowed

- src/main/java/org/accounting/system/endpoints/InstallationEndpoint.java
- src/main/java/org/accounting/system/endpoints/ProviderEndpoint.java
- src/main/java/org/accounting/system/entities/installation/Installation.java
- src/main/java/org/accounting/system/entities/projections/InstallationProjection.java
- src/main/java/org/accounting/system/repositories/HierarchicalRelationRepository.java
- src/main/java/org/accounting/system/repositories/acl/AccessControlRepository.java
- src/main/java/org/accounting/system/repositories/installation/InstallationModulator.java
- src/main/java/org/accounting/system/repositories/installation/InstallationRepository.java
- src/main/java/org/accounting/system/repositories/metric/MetricRepository.java
- src/main/java/org/accounting/system/repositories/modulators/AccessModulator.java
- src/main/java/org/accounting/system/services/MetricDefinitionService.java
- src/main/java/org/accounting/system/services/MetricService.java
- src/main/java/org/accounting/system/services/ProjectService.java
- src/main/java/org/accounting/system/services/ProviderService.java
- src/main/java/org/accounting/system/services/installation/InstallationService.java
- src/main/java/org/accounting/system/util/QueryParser.java
> ACC-62 Add search on Installation

- src/main/java/org/accounting/system/services/client/ClientService.java
- src/main/resources/db/changeLog.xml
- src/test/java/org/accounting/system/MetricDefinitionAuthorizationTest.java
We have generated the Metric Definition Creator Role.
ACC-98
> [ACC-98] Metric Definition Role

- website/docs/installation.md
- website/docs/project.md
- website/docs/provider.md
add search request documentation in project.md, provider.md, instalaltion.md
> ACC-97 Document search feature in Project-Provider-Installation

- Jenkinsfile
- website/package.json
- Add a deploy docs stage in Jenkins file using docusaurus deploy command
- Fix github issue by slightly bumping the docusaurus minor version to the same one used in other argo projects (.63 from .61). We should though organise migration to the latest available.
> Add deployment of docs stage in Jenkinsfile

- src/main/java/org/accounting/system/entities/Metric.java
- src/main/java/org/accounting/system/entities/MetricDefinition.java
- src/main/java/org/accounting/system/entities/Project.java
- src/main/java/org/accounting/system/entities/installation/Installation.java
- src/main/java/org/accounting/system/entities/provider/Provider.java
- src/main/java/org/accounting/system/repositories/installation/InstallationRepository.java
- src/main/java/org/accounting/system/services/installation/InstallationService.java
- src/main/resources/db/changeLog.xml
- src/test/java/org/accounting/system/InstallationEndpointTest.java
The combination of the following Installation attributes {project, organisation, installation} should be unique. Therefore,
you cannot insert into the database two Installations with the same {project, organisation, installation}.
> Uniqueness of Installation

- pom.xml
- src/main/java/org/accounting/system/templates/LandingRoute.java
- src/main/resources/application.properties
- src/main/resources/templates/index.html
The index.html is rendered using the Qute Templating Engine.
> Creating index.html template

- src/main/java/org/accounting/system/endpoints/MetricEndpoint.java
- src/main/java/org/accounting/system/enums/Operand.java
- src/main/java/org/accounting/system/repositories/HierarchicalRelationRepository.java
- src/main/java/org/accounting/system/repositories/metric/MetricModulator.java
- src/main/java/org/accounting/system/repositories/metric/MetricRepository.java
- src/main/java/org/accounting/system/services/MetricService.java
- src/main/resources/db/changeLog.xml
Permissions in metrics to restrict client from retrieving metrics that should not access.
Add index to AccessControl collection under changeLog.xml
> ACC-104 Fix metrics permissions

- src/main/java/org/accounting/system/endpoints/ProjectEndpoint.java
- src/main/java/org/accounting/system/repositories/project/ProjectRepository.java
- src/main/java/org/accounting/system/services/ProjectService.java
- website/docs/api/project.md
Improvement in search() projects query in mongodb
> ACC-133 Improve search() projects mongodb query

- src/main/java/org/accounting/system/endpoints/ProviderEndpoint.java
- src/main/java/org/accounting/system/repositories/provider/ProviderRepository.java
- src/main/java/org/accounting/system/services/ProviderService.java
Improve queries for search() and getAll providers
> ACC-116 ACC-117 improve providers search and getall queries

- src/main/java/org/accounting/system/endpoints/MetricEndpoint.java
- src/main/java/org/accounting/system/entities/Metric.java
- src/main/java/org/accounting/system/entities/projections/MetricProjection.java
- src/main/java/org/accounting/system/repositories/installation/InstallationRepository.java
- src/main/java/org/accounting/system/repositories/metric/MetricRepository.java
- src/main/java/org/accounting/system/services/HierarchicalRelationService.java
- src/main/java/org/accounting/system/services/MetricService.java
- src/main/java/org/accounting/system/services/installation/InstallationService.java
> ACC-122 ACC-123 Improve search() Metrics mongodb query

- pom.xml
- src/main/java/org/accounting/system/endpoints/InstallationEndpoint.java
- src/main/java/org/accounting/system/endpoints/ProjectEndpoint.java
- src/main/java/org/accounting/system/entities/HierarchicalRelation.java
- src/main/java/org/accounting/system/repositories/HierarchicalRelationRepository.java
- src/main/java/org/accounting/system/repositories/installation/InstallationRepository.java
- src/main/java/org/accounting/system/repositories/metric/MetricRepository.java
- src/main/java/org/accounting/system/repositories/project/ProjectAccessAlwaysRepository.java
- src/main/java/org/accounting/system/repositories/project/ProjectAccessEntityRepository.java
- src/main/java/org/accounting/system/repositories/project/ProjectModulator.java
- src/main/java/org/accounting/system/repositories/project/ProjectRepository.java
- src/main/java/org/accounting/system/repositories/provider/ProviderAccessAlwaysRepository.java
- src/main/java/org/accounting/system/repositories/provider/ProviderAccessEntityRepository.java
- src/main/java/org/accounting/system/repositories/provider/ProviderModulator.java
- src/main/java/org/accounting/system/services/HierarchicalRelationService.java
- src/main/java/org/accounting/system/services/MetricService.java
- src/main/java/org/accounting/system/services/ProjectService.java
- src/main/java/org/accounting/system/services/ProviderService.java
- src/main/java/org/accounting/system/services/installation/InstallationService.java
- src/main/java/org/accounting/system/util/Utility.java
- src/main/java/org/accounting/system/validators/ValidateStartEndTimestampValidator.java
- src/test/java/org/accounting/system/MetricEndpointTest.java
- website/docs/api/collect_metrics.md
We have enhanced metric endpoints by adding date filtering
> Date Filtering in Metrics

- src/main/java/org/accounting/system/endpoints/ClientEndpoint.java
- src/main/java/org/accounting/system/endpoints/InstallationEndpoint.java
- src/main/java/org/accounting/system/endpoints/MetricDefinitionEndpoint.java
- src/main/java/org/accounting/system/endpoints/MetricEndpoint.java
- src/main/java/org/accounting/system/endpoints/ProjectEndpoint.java
- src/main/java/org/accounting/system/endpoints/ProviderEndpoint.java
- src/main/java/org/accounting/system/endpoints/RoleEndpoint.java
- src/main/java/org/accounting/system/services/ProjectService.java
Add extra permissions to project_admin
> Project Admin Permissions

- src/main/java/org/accounting/system/endpoints/MetricDefinitionEndpoint.java
- website/docs/api/installation.md
- website/docs/api/metric.md
- website/docs/api/metric_definition.md
- website/docs/api/project.md
- website/docs/api/provider.md
- website/docs/guides/_category_.json
- website/docs/guides/search_filter.md
Added in documentation , in guides section, guidelines about how to syntax a search filter.
Changes occured in api description to link search requests in this page. also in metrics and  metric definitions , the search request description is added
> ACC-152 ACC-153 Accounting guide missing documentation & add search filter syntax documentation

- website/docs/api/installation.md
- website/docs/api/metric.md
- website/docs/api/metric_definition.md
- website/docs/api/project.md
- website/docs/api/provider.md
- website/docs/guides/search_filter.md
minor fixes on documentation. a broken link fixed, as well as a false arithmesis of sections
> minor fix in documentation

- website/docs/guides/installations.md
- website/docs/guides/search_filter.md
This pr includes the guidelines to manage installations. installation.md describes the guidelens
> ACC-149 Add guidelines for managing installations

- src/main/java/org/accounting/system/endpoints/ClientEndpoint.java
- src/main/java/org/accounting/system/endpoints/ProjectEndpoint.java
- src/main/java/org/accounting/system/endpoints/ProviderEndpoint.java
- src/main/java/org/accounting/system/entities/acl/AccessControl.java
- src/main/java/org/accounting/system/entities/projections/ProviderProjectionWithProjectInfo.java
- src/main/java/org/accounting/system/entities/projections/normal/ProjectProjection.java
- src/main/java/org/accounting/system/entities/projections/normal/ProjectionInstallation.java
- src/main/java/org/accounting/system/entities/projections/normal/ProviderProjection.java
- src/main/java/org/accounting/system/entities/projections/permissions/ProjectProjectionWithPermissions.java
- src/main/java/org/accounting/system/entities/projections/permissions/ProjectionInstallationWithPermissions.java
- src/main/java/org/accounting/system/entities/projections/permissions/ProviderProjectionWithPermissions.java
- src/main/java/org/accounting/system/enums/Collection.java
- src/main/java/org/accounting/system/enums/Operation.java
- src/main/java/org/accounting/system/mappers/RoleMapper.java
- src/main/java/org/accounting/system/repositories/project/ProjectRepository.java
- src/main/java/org/accounting/system/repositories/provider/ProviderRepository.java
- src/main/java/org/accounting/system/services/ProjectService.java
- src/main/java/org/accounting/system/services/ProviderService.java
- src/main/java/org/accounting/system/services/authorization/RoleService.java
- src/main/java/org/accounting/system/services/installation/InstallationService.java
- src/main/resources/db/changeLog.xml
- src/test/java/org/accounting/system/ProjectAutorizationTest.java
We have generated a new endpoint returning the client permissions upon different projects, providers, and installations.
> Returning the client permissions

- src/main/java/org/accounting/system/dtos/enums/EnumResponseDto.java
- src/main/java/org/accounting/system/endpoints/OperandEndpoint.java
- src/main/java/org/accounting/system/endpoints/OperatorEndpoint.java
- src/main/java/org/accounting/system/entities/projections/permissions/ProviderProjectionWithPermissions.java
- src/main/java/org/accounting/system/enums/Operand.java
- src/main/java/org/accounting/system/enums/Operator.java
- src/main/java/org/accounting/system/mappers/EnumMapper.java
- website/docs/api/metric_definition.md
- website/docs/guides/search_filter.md
Created request to retrieve Operators and  request to retrieve Operands , in a list.
> ACC-157 Request api to retrieve list of the operators and operands ENUMS

- website/docs/guides/api_actions/installations.md
- website/docs/guides/api_actions/projects.md
- website/docs/guides/api_actions/providers.md
- website/docs/guides/api_actions/search_filter.md
projects.md added under guides section
> ACC-151 Add guidelines for managing projects

- website/docs/guides/api_actions/metric_definitions.md
- website/docs/guides/api_actions/search_filter.md
Added metric-definitions.md under guides to describe the guidelines documentation of managing metric definitions
> Accounting guide metric definitions

- website/docs/guides/api_actions/installations.md
- website/docs/guides/api_actions/metric_definitions.md
- website/docs/guides/api_actions/metrics.md
- website/docs/guides/api_actions/search_filter.md
add metrics.md to document guidelines of how to manage metrics
> ACC-155 Add guidelines for managing metrics

- website/docs/guides/api_actions/installations.md
- website/docs/guides/api_actions/metric_definitions.md
- website/docs/guides/api_actions/metrics.md
- website/docs/guides/api_actions/projects.md
- website/docs/guides/api_actions/providers.md
- website/docs/guides/api_actions/register.md
- website/docs/guides/api_actions/search_filter.md
register.md added to describe guidelines of how to register accounting system
> ACC-156 Add guidelines for register system

- src/main/resources/application.properties
The aai proxy url has been changed, so we have to refresh the application.properties as well.
> Change AAI Proxy URL

- src/main/java/org/accounting/system/dtos/installation/InstallationRequestDto.java
- src/main/java/org/accounting/system/validators/AccessProviderValidator.java
- src/test/java/org/accounting/system/InstallationEndpointTest.java
In Installation , infrastracture field changed to be optional.
> ACC-160 Change Infrastructure in Installation to optional

- src/main/java/org/accounting/system/dtos/installation/UpdateInstallationRequestDto.java
- src/main/java/org/accounting/system/services/installation/InstallationService.java
- src/test/java/org/accounting/system/InstallationEndpointTest.java
- src/test/java/org/accounting/system/MetricEndpointTest.java
> fix to update installation

- src/main/java/org/accounting/system/endpoints/SystemAdminEndpoint.java
- src/main/java/org/accounting/system/interceptors/SystemAdminInterceptor.java
- src/main/java/org/accounting/system/interceptors/annotations/SystemAdmin.java
- src/main/java/org/accounting/system/repositories/client/ClientRepository.java
- src/main/java/org/accounting/system/repositories/project/ProjectRepository.java
- src/main/java/org/accounting/system/services/SystemAdminService.java
- src/main/java/org/accounting/system/util/Utility.java
- src/test/java/org/accounting/system/InstallationAuthorizationTest.java
- src/test/java/org/accounting/system/InstallationEndpointTest.java
- src/test/java/org/accounting/system/MetricEndpointTest.java
- src/test/java/org/accounting/system/ProjectAutorizationTest.java
- src/test/java/org/accounting/system/ProjectEndpointTest.java
- src/test/java/org/accounting/system/ProviderEndpointTest.java
- website/docs/guides/api_actions/projects.md
- website/docs/guides/api_actions/providers.md
When a system admin submits a Project through API, the Project is registered to all admins.
> System Admin improvements

- CHANGELOG.md
- src/main/java/org/accounting/system/clients/AAIProxyClient.java
- src/main/java/org/accounting/system/health/AAIProxyHealthCheck.java
- src/main/resources/application.properties
We have created a readiness health check to check if the AAI proxy is up and can authenticate the clients.
> [ACC-190] Accounting Service health checks

- CHANGELOG.md
- CITATION.cff
- CODE_OF_CODUCT.md
- CONTRIBUTING.md
CITATION.cff, CODE_OF_CODUCT.md, CONTRIBUTING.md
ACC-191
> Add additional files

- pom.xml
Bump version to 1.1.0 in pom.xml
> Bump version number to 1.1.0 in pom

- CHANGELOG.md
- src/main/java/org/accounting/system/dtos/client/ClientResponseDto.java
- src/main/java/org/accounting/system/endpoints/ProviderEndpoint.java
- src/main/java/org/accounting/system/endpoints/SystemAdminEndpoint.java
- src/main/java/org/accounting/system/entities/Project.java
- src/main/java/org/accounting/system/entities/provider/Provider.java
- src/main/java/org/accounting/system/services/ProviderService.java
- src/main/java/org/accounting/system/services/SystemAdminService.java
> [ACC-322] Fix Project and Provider not to accept full stop in id when are generated

- website/docs/policies/_category_.json
- website/docs/policies/privacy.md
Add Privacy Policy in the doc under Policies section.
> Add Privacy Policy in doc

- website/docusaurus.config.js
- removed reference to SRCE that was as copy paste left over.
> Update docusaurus.config.js  fix footer

- src/main/java/org/accounting/system/templates/OidcClientTemplate.java
- src/main/resources/application.properties
- src/main/resources/templates/client.html
We have added the offline_access client scope in order to receive via access_token a refresh token.
> Add offline_access to client scope

- .github/workflows/docs.yml
- Jenkinsfile
- website/package-lock.json
- website/package.json
Update docusaurus to 3.8.1. 
Add github action to deploy docs
> Update docusaurus to 3.8.1. Add github action to deploy docs

- website/docs/api/installation.md
- website/docs/api/project.md
- website/docs/api/provider.md
- website/docs/guides/api_actions/installations.md
- website/docs/guides/api_actions/projects.md
- website/docs/guides/api_actions/providers.md
This PR adds documentation for the Installation, Project, and Provider report endpoints, including request examples, parameters, responses, and short reference notes in the guides.
> Add documentation for project, provider, installation reports

- website/docs/policies/privacy.md
- website/docs/policies/terms.md
- Added Terms of Use.
- Applied minor fixes and adjustments in PP for consistency.
> [ACC-394] Add Terms of Use and Privacy Policy minor fix
